### ISSUE TITLE
Handwriting fonts are not applied for modal dialogs

### ISSUE THREAD

**Issue by vividtone** [akiko-pusu/redmine_theme_kodomo_midori#18]
Modal dialogs are displayed with Arial or Helvetica fonts instead of handwriting fonts. The cause of the issue is that `font-style` for `.ui-widget` class is not overridden.

Confirmed with:
* Redmine 4.1.1, trunk (r19815)
* Kodomo Redmine Midori v0.0.9

 <img width="1021" alt="image" src="https://user-images.githubusercontent.com/114863/84580821-9e345f00-ae15-11ea-8baa-1e04592df17e.png">

**Comment by akiko-pusu** [comment]
Thanks for the above screenshot! It's very helpful and I've confirmed it.

**Comment by akiko-pusu** [comment]
Fixed on commit: f8d2fef
Thanks!
